version: "3.7"
services: 
    org-db:
      image: "mysql:8.0.31"
      restart: on-failure
      ports: 
        - 3306:3306
      volumes:
        - ./org-mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: organizationdb
        MYSQL_ROOT_PASSWORD: 1234 
    emp-db:
      image: "mysql:8.0.31"
      restart: on-failure
      ports: 
        - 3307:3306
      volumes:
        - ./emp-mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: employeedb
        MYSQL_ROOT_PASSWORD: 1234
    # organization-service:
    #   build:
    #     context: ./organization-service
    #     dockerfile: Dockerfile
    #   restart: on-failure
    #   ports:
    #     - 8080:8080
    #   environment:
    #     DB_HOST: mysql
    #     DB_USERNAME: root
    #     DB_PASSWORD: 1234
    #     DB_NAME: organizationdb
    # employee-service:
    #   build:
    #     context: ./employee-service
    #     dockerfile: Dockerfile
    #   restart: on-failure
    #   ports:
    #     - 8081:8081
    #   environment:
    #     DB_HOST: mysql
    #     DB_USERNAME: root
    #     DB_PASSWORD: 1234
    #     DB_NAME: organizationdb
    #     ORG_SERVICE_URL: organization-service:8080
      

