# helmfile for demo
# we can add repos in helmfile
# repositories:
# - name : <repository-name>
#   url: <url>

templates:
  organization-service: &organization-service
    namespace: default
    chart: ./organization-service-chart
  employee-service: &employee-service
    namespace: default
    chart: ./employee-service-chart
  

releases:
- name: mysql
  namespace: default
  chart: ./mysql-chart
- name: organization-service
  <<: *organization-service
- name: employee-service
  <<: *employee-service

# - name: organization-service
#   namespace: default
#   chart: ./organization-chart
#   values:
#   - ./test-values.yaml
#   installed: true
