apiVersion: v1
kind: Secret
metadata:
   name: {{.Release.Name }}-db-secrets
type: Opaque
data:
    mysql-username: {{ .Values.db_secrets.username }}
    mysql-password: {{ .Values.db_secrets.password }}
   #  mysql-username: cm9vdA==
   #  mysql-password: MTIzNA==
