server: 
    port: 8080
    
spring:
    datasource:
#        url: jdbc:mysql://${DB_HOST}/${DB_NAME}
        url: jdbc:mysql://localhost:3306/organizationdb
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
#        username: ${DB_USERNAME}
#        password: ${DB_PASSWORD}
    jpa: 
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate: 
            ddl-auto: update
    kafka:
        boostrap-servers: localhost:9092
        
org.topic.name: org_events
dept.topic.name: dept_events        
                               
